# -*- coding: utf-8 -*-
"""Penguins_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2kn0t2gTwHrwNve82CvMKUyOS1meka2
"""

#  Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

print("Hello Colab!")

# For better visuals
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

# Pandas display settings to show all columns in one line
pd.set_option('display.max_columns', None)   # Show all columns
pd.set_option('display.width', None)         # Don't wrap to next line
pd.set_option('display.max_colwidth', None)  # Show full content in each cell

#  Load dataset
df = pd.read_csv("penguins.csv")

# Basic exploration
print("\n--- First 5 Rows ---")
print(df.head())

print("\n--- Shape of Dataset ---")
print(df.shape)

print("\n--- Data Info ---")
print(df.info())

print("\n--- Statistical Summary ---")
print(df.describe())

# Missing values
print("\n--- Missing Values ---")
print(df.isnull().sum())

#  Unique values in categorical columns
print("\n--- Unique Categorical Values ---")
for col in df.select_dtypes(include='object'):
    print(f"{col}: {df[col].unique()}")

#  Data Cleaning
# Drop rows with missing values
df.dropna(inplace=True)

# Check duplicates
duplicates = df.duplicated().sum()
print(f"\n--- Duplicate Rows: {duplicates} ---")

#  Univariate Analysis
# Histograms for numeric columns
df.hist(figsize=(12, 8), bins=20, edgecolor='black')
plt.suptitle("Histogram of Numeric Columns", fontsize=16)
plt.show()

# Boxplots for numeric columns
for col in df.select_dtypes(include=np.number):
    sns.boxplot(x=df[col], hue=None, color='skyblue')
    plt.title(f"Boxplot of {col}")
    plt.show()

# Countplots for categorical columns
for col in df.select_dtypes(include='object'):
    sns.countplot(x=col, hue=None, data=df, palette="pastel")
    plt.title(f"Countplot of {col}")
    plt.show()

# Bivariate Analysis
# Pairplot
sns.pairplot(df, hue="species", palette="husl")
plt.suptitle("Pairplot by Species", y=1.02)
plt.show()

# Scatterplot: flipper length vs body mass
sns.scatterplot(
    x="flipper_length_mm",
    y="body_mass_g",
    hue="species",
    style="island",
    data=df,
    palette="Set2"
)
plt.title("Flipper Length vs Body Mass by Species")
plt.show()

# Group statistics by species
print("\n--- Mean values grouped by Species ---")
print(df.groupby("species").mean(numeric_only=True))

#  Correlation Analysis
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

#  Observations
print("""
==========================
OBSERVATIONS
==========================
1. Histogram: Body mass, flipper length, and bill length show distinct peaks for different species. Gentoo penguins cluster at higher body mass values (~5,000 g).
2. Boxplots: Adelie species have a smaller range in body mass and flipper length compared to Gentoo. Some outliers exist in body mass for Chinstrap.
3. Countplots: Adelie penguins are the most represented species, with balanced gender distribution except for some missing gender data.
4. Pairplot: Flipper length and body mass have a strong positive relationship, especially within species clusters.
5. Scatterplot: Gentoo species clearly separate from Adelie and Chinstrap in both metrics, forming a distinct cluster.
6. Heatmap: Flipper length and body mass have the highest positive correlation (~0.87). Bill length and bill depth have a moderate negative correlation.
""")

#  Summary
print("""
==========================
SUMMARY OF FINDINGS
==========================
- The dataset contains three main species (Adelie, Chinstrap, Gentoo) with varying body sizes and morphological characteristics.
- Gentoo penguins are significantly larger in both body mass and flipper length compared to the other species.
- Adelie penguins are the smallest in overall size but have a relatively consistent body structure.
- Strong correlation exists between flipper length and body mass across all species, suggesting a proportional relationship.
- Gender distribution is fairly balanced, though some missing values exist.
- Potential outliers in Chinstrap body mass may require further investigation.
""")